spring:
  application:
    name: mackenzie-auth-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/mackenzie_auth
      auto-index-creation: true
  
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - User.Read
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Microsoft
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: userPrincipalName
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys

# Configurações JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 horas em milissegundos
  refresh-expiration: 604800000 # 7 dias em milissegundos

# Configurações de Email permitidos
mackenzie:
  allowed-email-domains:
    - mackenzie.br
    - mackenzista.com.br
  
  # Roles padrão
  default-roles:
    - ROLE_USER
  
  admin-emails:
    - admin@mackenzie.br

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Logging
logging:
  level:
    root: INFO
    br.mackenzie: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
# Profile: Docker
spring:
  config:
    activate:
      on-profile: docker
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

logging:
  level:
    root: INFO
    br.mackenzie: INFO
    org.springframework.security: INFO

---
# Profile: Production
spring:
  config:
    activate:
      on-profile: prod
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

jwt:
  expiration: 3600000 # 1 hora em produção

logging:
  level:
    root: WARN
    br.mackenzie: INFO
    org.springframework.security: WARN
